### PR TITLE
BT slide content added

### PR DESCRIPTION
**Pull request by brtarran**
@nrennie @andreas27 

I've added introductory slides as discussed. Is there anything else you need me to work on ahead of our Friday meeting?

### CODE REVIEW

**Review by nrennie — APPROVED** [review]
LGTM

**Comment by andreas27** [comment]
> @nrennie @andreas27
> 
> I've added introductory slides as discussed. Is there anything else you need me to work on ahead of our Friday meeting?

Looks all good to me, thank you!

Two comments:
- „Andreas and Nicola responded to the call“: were there really only two responses? That would be a bit sobering and perhaps you could rephrase that gently to look better.
- Nicola, perhaps you could refer in some locations to the first part, mine, for example when you introduce the color schemes (I am going to say that color schemes can be used to introduce an order), etc.

**Comment by nrennie** [comment]
> Andreas and Nicola responded to the call“: were there really only two responses? That would be a bit sobering and perhaps you could rephrase that gently to look better.
I didn't interpret this sentence that way at all... 

> Nicola, perhaps you could refer in some locations to the first part, mine, for example when you introduce the color schemes (I am going to say that color schemes can be used to introduce an order), etc.
If you talk about colour, I would refer to it verbally but I wouldn't duplicate information on slides (I tend to use slides as starting points). I would ask that if you're talking about colour, you also refer to the fact I'll discuss it later in more detail. On that note, I'm still concerned about the length of the slide deck at the moment (~90 slides for ~40 mins of talking) and was going to suggest that we consider whether both of us need to discuss colour scales. Let's discuss later.

**Comment by andreas27** [comment]
> > Andreas and Nicola responded to the call“: were there really only two responses? That would be a bit sobering and perhaps you could rephrase that gently to look better.
> 
> I didn't interpret this sentence that way at all...
Let‘s just leave it to Brian.

> > Nicola, perhaps you could refer in some locations to the first part, mine, for example when you introduce the color schemes (I am going to say that color schemes can be used to introduce an order), etc.
> 
> If you talk about colour, I would refer to it verbally but I wouldn't duplicate information on slides (I tend to use slides as starting points). I would ask that if you're talking about colour, you also refer to the fact I'll discuss it later in more detail. On that note, I'm still concerned about the length of the slide deck at the moment (~90 slides for ~40 mins of talking) and was going to suggest that we consider whether both of us need to discuss colour scales. Let's discuss later.

Suggestion:
- Color: OK. Anything to be changed with the slides? Talking is probably most efficient.
- No of slides:
  - Let’s remove the Napoleon slide.
  - I consider the section on tables, slides 38-43, as buffer. Leave them in but I can jump over them if time gets tight.

**Pull request merged**
